<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>rvs.AlgoTrader.Strategies</AssemblyName>
    <RootNamespace>rvs.AlgoTrader.Strategies</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\rvs.AlgoTrader.Domain\rvs.AlgoTrader.Domain.csproj" />
    <ProjectReference Include="..\rvs.AlgoTrader.Application\rvs.AlgoTrader.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NodaTime" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection.Abstractions" />
  </ItemGroup>
</Project>
