<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <AssemblyName>rvs.AlgoTrader.Brokers.Zerodha</AssemblyName>
    <RootNamespace>rvs.AlgoTrader.Brokers.Zerodha</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\rvs.AlgoTrader.Brokers.Abstractions\rvs.AlgoTrader.Brokers.Abstractions.csproj" />
    <ProjectReference Include="..\rvs.AlgoTrader.Application\rvs.AlgoTrader.Application.csproj" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Polly" />
    <PackageReference Include="NodaTime" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
    <PackageReference Include="Microsoft.Extensions.Options" />
  </ItemGroup>
</Project>
