using QuestPDF.Fluent;
using QuestPDF.Helpers;
using QuestPDF.Infrastructure;
using rvs.AlgoTrader.Application.DTOs.Backtest;

namespace rvs.AlgoTrader.Infrastructure.Services;

/// <summary>
/// Generates a printable PDF strategy report from a completed BacktestResultDto.
/// Uses QuestPDF (FOSS licence — community use).
/// </summary>
public static class BacktestReportGenerator
{
    // ── Colour constants (dark-finance palette) ──────────────────────────────
    private static readonly Color BgPage    = Color.FromHex("#0d0d17");
    private static readonly Color BgSection = Color.FromHex("#111120");
    private static readonly Color BorderCol = Color.FromHex("#1a1a2e");
    private static readonly Color TextPri   = Color.FromHex("#e2e8f0");
    private static readonly Color TextSub   = Color.FromHex("#94a3b8");
    private static readonly Color TextMuted = Color.FromHex("#4a5568");
    private static readonly Color ColGreen  = Color.FromHex("#00d07a");
    private static readonly Color ColRed    = Color.FromHex("#ff4757");
    private static readonly Color ColBlue   = Color.FromHex("#3b82f6");
    private static readonly Color ColAmber  = Color.FromHex("#f59e0b");

    public static byte[] Generate(BacktestResultDto result)
    {
        QuestPDF.Settings.License = LicenseType.Community;

        return Document.Create(container =>
        {
            container.Page(page =>
            {
                page.Size(PageSizes.A4);
                page.Margin(30);
                page.Background().Background(BgPage);
                page.DefaultTextStyle(t => t.FontFamily("Arial").FontSize(9).FontColor(TextPri));

                page.Header().Element(ComposeHeader(result));
                page.Content().Element(ComposeBody(result));
                page.Footer().AlignCenter().Text(t =>
                {
                    t.Span("Generated by rvs.AlgoTrader  ·  ").FontColor(TextMuted).FontSize(8);
                    t.CurrentPageNumber().FontColor(TextMuted).FontSize(8);
                    t.Span(" / ").FontColor(TextMuted).FontSize(8);
                    t.TotalPages().FontColor(TextMuted).FontSize(8);
                });
            });
        }).GeneratePdf();
    }

    // ── Header ───────────────────────────────────────────────────────────────
    private static Action<IContainer> ComposeHeader(BacktestResultDto r)
    {
        return c => c
            .BorderBottom(1).BorderColor(BorderCol)
            .PaddingBottom(8)
            .Row(row =>
            {
                row.RelativeItem().Column(col =>
                {
                    col.Item().Text(r.StrategyName).FontSize(16).Bold().FontColor(ColBlue);
                    col.Item().Text($"{r.Symbol}  ·  {r.Timeframe}  ·  {r.FromDate:dd MMM yyyy} – {r.ToDate:dd MMM yyyy}")
                        .FontSize(10).FontColor(TextSub);
                });
                row.ConstantItem(120).AlignRight().Column(col =>
                {
                    col.Item().Text("STRATEGY REPORT").FontSize(8).Bold().FontColor(TextMuted)
                        .LetterSpacing(0.08f);
                    col.Item().Text(r.StartedAt.HasValue
                        ? r.StartedAt.Value.ToLocalTime().ToString("dd MMM yyyy HH:mm")
                        : "--")
                        .FontSize(8).FontColor(TextMuted);
                });
            });
    }

    // ── Body ─────────────────────────────────────────────────────────────────
    private static Action<IContainer> ComposeBody(BacktestResultDto r)
    {
        return c => c.Column(col =>
        {
            // Circuit breaker warning
            if (r.CircuitBreakerHit)
            {
                col.Item().PaddingTop(8)
                    .Background(Color.FromHex("#431407"))
                    .Border(1).BorderColor(Color.FromHex("#f97316"))
                    .Padding(10)
                    .Text($"⚡ CIRCUIT BREAKER — {r.CircuitBreakerReason ?? "Equity fell below threshold"}")
                    .FontSize(9).Bold().FontColor(Color.FromHex("#fb923c"));
            }

            // Core metrics grid
            col.Item().PaddingTop(12).Element(ComposeMetricsGrid(r));

            // Risk-adjusted ratios
            col.Item().PaddingTop(10).Element(ComposeRatiosGrid(r));

            // Yearly breakdown
            if (r.YearlyBreakdown?.Count > 0)
                col.Item().PaddingTop(10).Element(ComposeYearlyTable(r));

            // Monthly P&L heatmap
            if (r.MonthlyBreakdown?.Count > 0)
                col.Item().PaddingTop(10).Element(ComposeMonthlyTable(r));

            // Trade journal
            if (r.Trades?.Count > 0)
                col.Item().PaddingTop(10).Element(ComposeTradeTable(r));
        });
    }

    // ── Core metrics ─────────────────────────────────────────────────────────
    private static Action<IContainer> ComposeMetricsGrid(BacktestResultDto r)
    {
        var pnlColor  = r.TotalPnl  >= 0 ? ColGreen : ColRed;
        var retColor  = r.TotalReturn >= 0 ? ColGreen : ColRed;
        var ddColor   = ColRed;

        return c => c
            .Background(BgSection).Border(1).BorderColor(BorderCol).Padding(10)
            .Column(col =>
            {
                col.Item().Text("PERFORMANCE SUMMARY")
                    .FontSize(8).Bold().FontColor(TextMuted).LetterSpacing(0.06f);
                col.Item().PaddingTop(8).Row(row =>
                {
                    MetricCell(row, "Net P&L",        Inr(r.TotalPnl),                 pnlColor);
                    MetricCell(row, "Return",          $"{r.TotalReturn*100:F2}%",       retColor);
                    MetricCell(row, "Win Rate",        $"{r.WinRate*100:F1}%",           TextPri);
                    MetricCell(row, "Total Trades",    r.TotalTrades.ToString(),         TextPri);
                    MetricCell(row, "Max Drawdown",    $"{r.MaxDrawdown*100:F1}%",       ddColor);
                    MetricCell(row, "Initial Capital", Inr(r.InitialCapital),            TextPri);
                    MetricCell(row, "Final Equity",    Inr(r.FinalEquity),               r.FinalEquity >= r.InitialCapital ? ColGreen : ColRed);
                });
            });
    }

    // ── Risk-adjusted ratios ──────────────────────────────────────────────────
    private static Action<IContainer> ComposeRatiosGrid(BacktestResultDto r)
    {
        return c => c
            .Background(BgSection).Border(1).BorderColor(BorderCol).Padding(10)
            .Column(col =>
            {
                col.Item().Text("RISK-ADJUSTED METRICS")
                    .FontSize(8).Bold().FontColor(TextMuted).LetterSpacing(0.06f);
                col.Item().PaddingTop(8).Row(row =>
                {
                    MetricCell(row, "Sharpe",         r.SharpeRatio.ToString("F2"),   r.SharpeRatio >= 1 ? ColGreen : ColAmber);
                    MetricCell(row, "Sortino",        r.SortinoRatio.ToString("F2"),  r.SortinoRatio >= 1 ? ColGreen : ColAmber);
                    MetricCell(row, "Calmar",         r.CalmarRatio.ToString("F2"),   TextPri);
                    MetricCell(row, "Profit Factor",  r.ProfitFactor.ToString("F2"),  r.ProfitFactor >= 1.5m ? ColGreen : ColAmber);
                    MetricCell(row, "Expectancy",     Inr(r.ExpectancyPerTrade),      r.ExpectancyPerTrade >= 0 ? ColGreen : ColRed);
                    MetricCell(row, "Avg Win",        Inr(r.AvgWin),                  ColGreen);
                    MetricCell(row, "Avg Loss",       Inr(r.AvgLoss),                 ColRed);
                    MetricCell(row, "Max Consec. Loss", r.MaxConsecutiveLosses.ToString(), ColAmber);
                });
            });
    }

    // ── Yearly table ──────────────────────────────────────────────────────────
    private static Action<IContainer> ComposeYearlyTable(BacktestResultDto r)
    {
        return c => c
            .Background(BgSection).Border(1).BorderColor(BorderCol).Padding(10)
            .Column(col =>
            {
                col.Item().Text("YEAR-BY-YEAR BREAKDOWN")
                    .FontSize(8).Bold().FontColor(TextMuted).LetterSpacing(0.06f);
                col.Item().PaddingTop(6).Table(t =>
                {
                    t.ColumnsDefinition(cd =>
                    {
                        cd.RelativeColumn(1);
                        cd.RelativeColumn(2);
                        cd.RelativeColumn(2);
                        cd.RelativeColumn(1);
                        cd.RelativeColumn(1);
                    });

                    // Header row
                    foreach (var h in new[] { "Year", "Net P&L", "Return", "Trades", "Win%" })
                        t.Header(h2 => h2.Cell().Background(BorderCol).Padding(3).AlignCenter()
                            .Text(h).FontSize(8).Bold().FontColor(TextMuted));

                    // Data rows
                    foreach (var y in r.YearlyBreakdown!)
                    {
                        var bg = y.Pnl > 0 ? Color.FromHex("#00200f") : y.Pnl < 0 ? Color.FromHex("#1a0000") : BgSection;
                        var pCol = y.Pnl >= 0 ? ColGreen : ColRed;
                        t.Cell().Background(bg).BorderBottom(1).BorderColor(BorderCol).Padding(3)
                            .Text(y.Year.ToString()).FontSize(8).Bold().FontColor(TextPri);
                        t.Cell().Background(bg).BorderBottom(1).BorderColor(BorderCol).Padding(3)
                            .Text(Inr(y.Pnl)).FontSize(8).FontColor(pCol);
                        t.Cell().Background(bg).BorderBottom(1).BorderColor(BorderCol).Padding(3)
                            .Text($"{y.Return*100:F1}%").FontSize(8).FontColor(pCol);
                        t.Cell().Background(bg).BorderBottom(1).BorderColor(BorderCol).Padding(3)
                            .Text(y.Trades.ToString()).FontSize(8).FontColor(TextPri);
                        t.Cell().Background(bg).BorderBottom(1).BorderColor(BorderCol).Padding(3)
                            .Text($"{y.WinRate*100:F0}%").FontSize(8).FontColor(TextPri);
                    }
                });
            });
    }

    // ── Monthly heatmap table ─────────────────────────────────────────────────
    private static readonly string[] MonthNames =
        ["Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Nov","Dec"];

    private static Action<IContainer> ComposeMonthlyTable(BacktestResultDto r)
    {
        var years = r.MonthlyBreakdown!.Select(m => m.Year).Distinct().OrderBy(y => y).ToList();

        return c => c
            .Background(BgSection).Border(1).BorderColor(BorderCol).Padding(10)
            .Column(col =>
            {
                col.Item().Text("MONTHLY P&L")
                    .FontSize(8).Bold().FontColor(TextMuted).LetterSpacing(0.06f);
                col.Item().PaddingTop(6).Table(t =>
                {
                    t.ColumnsDefinition(cd =>
                    {
                        cd.ConstantColumn(30); // Year
                        for (int i = 0; i < 12; i++) cd.RelativeColumn(1);
                    });

                    // Month headers
                    t.Header(h2 =>
                    {
                        h2.Cell().Background(BorderCol).Padding(2).Text("").FontSize(7);
                        foreach (var m in MonthNames)
                            h2.Cell().Background(BorderCol).Padding(2).AlignCenter()
                                .Text(m).FontSize(7).Bold().FontColor(TextMuted);
                    });

                    // One row per year
                    foreach (var year in years)
                    {
                        t.Cell().Background(BgSection).BorderBottom(1).BorderColor(BorderCol)
                            .Padding(2).Text(year.ToString()).FontSize(7).Bold().FontColor(TextPri);

                        for (int month = 1; month <= 12; month++)
                        {
                            var entry = r.MonthlyBreakdown!.FirstOrDefault(m => m.Year == year && m.Month == month);
                            if (entry == null)
                            {
                                t.Cell().Background(BgSection).BorderBottom(1).BorderColor(BorderCol).Padding(2).Text("--").FontSize(7).FontColor(TextMuted);
                            }
                            else
                            {
                                var bg = entry.Pnl > 0 ? Color.FromHex("#00200f") : entry.Pnl < 0 ? Color.FromHex("#200005") : BgSection;
                                var fc = entry.Pnl >= 0 ? ColGreen : ColRed;
                                t.Cell().Background(bg).BorderBottom(1).BorderColor(BorderCol)
                                    .Padding(2).AlignCenter()
                                    .Text(ShortInr(entry.Pnl)).FontSize(7).FontColor(fc);
                            }
                        }
                    }
                });
            });
    }

    // ── Trade journal ─────────────────────────────────────────────────────────
    private static Action<IContainer> ComposeTradeTable(BacktestResultDto r)
    {
        var trades = r.Trades!.Take(200).ToList(); // cap at 200 rows to keep PDF manageable

        return c => c
            .Background(BgSection).Border(1).BorderColor(BorderCol).Padding(10)
            .Column(col =>
            {
                col.Item().Text($"TRADE JOURNAL  ({trades.Count}{(r.Trades!.Count > 200 ? " of " + r.Trades.Count : "")} trades)")
                    .FontSize(8).Bold().FontColor(TextMuted).LetterSpacing(0.06f);
                col.Item().PaddingTop(6).Table(t =>
                {
                    t.ColumnsDefinition(cd =>
                    {
                        cd.RelativeColumn(2); // Entry time
                        cd.RelativeColumn(2); // Exit time
                        cd.RelativeColumn(1); // Dir
                        cd.RelativeColumn(1); // Qty
                        cd.RelativeColumn(2); // Entry
                        cd.RelativeColumn(2); // Exit
                        cd.RelativeColumn(2); // Net P&L
                        cd.RelativeColumn(2); // Exit reason
                    });

                    t.Header(h2 =>
                    {
                        foreach (var h in new[] { "Entry Time", "Exit Time", "Dir", "Qty", "Entry ₹", "Exit ₹", "Net P&L", "Reason" })
                            h2.Cell().Background(BorderCol).Padding(3).Text(h).FontSize(7).Bold().FontColor(TextMuted);
                    });

                    foreach (var tr in trades)
                    {
                        var dirColor = tr.Direction == "BUY" ? ColGreen : ColRed;
                        var pnlColor = tr.NetPnl >= 0 ? ColGreen : ColRed;
                        var bg       = tr.NetPnl >= 0 ? Color.FromHex("#0a2218") : Color.FromHex("#1f0a0a");

                        t.Cell().Background(bg).BorderBottom(1).BorderColor(BorderCol).Padding(3)
                            .Text(FormatUtcToIst(tr.EntryTime)).FontSize(7).FontColor(TextSub);
                        t.Cell().Background(bg).BorderBottom(1).BorderColor(BorderCol).Padding(3)
                            .Text(FormatUtcToIst(tr.ExitTime)).FontSize(7).FontColor(TextSub);
                        t.Cell().Background(bg).BorderBottom(1).BorderColor(BorderCol).Padding(3)
                            .Text(tr.Direction).FontSize(7).Bold().FontColor(dirColor);
                        t.Cell().Background(bg).BorderBottom(1).BorderColor(BorderCol).Padding(3)
                            .Text(tr.Quantity.ToString()).FontSize(7).FontColor(TextPri);
                        t.Cell().Background(bg).BorderBottom(1).BorderColor(BorderCol).Padding(3)
                            .Text(Inr(tr.EntryPrice)).FontSize(7).FontColor(TextPri);
                        t.Cell().Background(bg).BorderBottom(1).BorderColor(BorderCol).Padding(3)
                            .Text(Inr(tr.ExitPrice)).FontSize(7).FontColor(TextPri);
                        t.Cell().Background(bg).BorderBottom(1).BorderColor(BorderCol).Padding(3)
                            .Text(Inr(tr.NetPnl)).FontSize(7).Bold().FontColor(pnlColor);
                        t.Cell().Background(bg).BorderBottom(1).BorderColor(BorderCol).Padding(3)
                            .Text(tr.ExitReason ?? "--").FontSize(7).FontColor(TextMuted);
                    }
                });
            });
    }

    // ── Helpers ───────────────────────────────────────────────────────────────
    private static void MetricCell(RowDescriptor row, string label, string value, Color valueColor)
    {
        row.RelativeItem().Column(col =>
        {
            col.Item().Text(label).FontSize(7).FontColor(TextMuted).Bold().LetterSpacing(0.05f);
            col.Item().Text(value).FontSize(11).Bold().FontColor(valueColor);
        });
    }

    private static string Inr(decimal v)
    {
        var sign = v < 0 ? "-" : v > 0 ? "+" : "";
        return $"{sign}₹{Math.Abs(v):N0}";
    }

    private static string ShortInr(decimal v)
    {
        var abs = Math.Abs(v);
        var sign = v < 0 ? "-" : "";
        if (abs >= 100_000) return $"{sign}{abs / 100_000:F1}L";
        if (abs >= 1_000)   return $"{sign}{abs / 1_000:F0}K";
        return $"{sign}{abs:F0}";
    }

    private static readonly TimeZoneInfo Ist =
        TimeZoneInfo.FindSystemTimeZoneById(
            OperatingSystem.IsWindows() ? "India Standard Time" : "Asia/Kolkata");

    private static string FormatUtcToIst(string? utcIso)
    {
        if (string.IsNullOrEmpty(utcIso)) return "--";
        if (!DateTimeOffset.TryParse(utcIso, out var dto)) return utcIso;
        var ist = TimeZoneInfo.ConvertTime(dto, Ist);
        return ist.ToString("dd/MM HH:mm");
    }
}
